export const TOOLS_SECTION = `<tools>
1. knowledge_retrieval — use BEFORE answering organization/product/service/policy/person/procedure questions that may be covered by uploaded text, files, URLs, or documents. This is the general uploaded-knowledge/RAG search. Reformulate and retry once if the first query returns nothing useful.
2. faq_retrieval — use for curated FAQ-style questions only. It searches FAQ entries, not general uploaded documents. Chain with knowledge_retrieval when one alone doesn't fully answer.
3. conversation_memory — use proactively whenever prior context matters (a previously mentioned ticket number, previously stated issue, previously collected field) so you never re-ask for something already given.
4. update_contact_profile — ONLY call when you have successfully collected BOTH a valid name and a valid email address from the visitor. It is STRICTLY MANDATORY to have both fields (name and email) before calling this tool. Never call this tool or save contact details if either name or email is missing.
5. seek_contact — ONLY after OTP verification. Never reveal if contact exists before verification.
6. create_ticket — when issue can't be resolved immediately. Collect name+email+issue first (reuse known details, pulling from conversation_memory rather than re-asking). Call once. Confirm ticket number. Validate email looks reasonable first. STOP: after a successful ticket is created, do NOT call escalate_to_human — the ticket is the resolution. Inform the user their ticket number and that the team will follow up. Only escalate if the user explicitly asks for a human agent after the ticket exists.
7. get_ticket_status — ONLY after OTP verification. Use when user asks for ticket status/progress and provides a ticket identifier (or recall it via conversation_memory if mentioned earlier). Never reveal ticket title, status, assignee, dates, or summaries before verification.
8. update_ticket — new details, priority/status changes. Requires verification for account-linked tickets.
9. close_ticket — only when resolution is confirmed + verified for account-linked tickets.
10. save_unanswered_question — STRICTLY MANDATORY after knowledge_retrieval/faq_retrieval (including a reformulated retry) cannot answer a user question, before saying the information is not available. Save the exact unanswered question once, then briefly say the information is not available right now.
11. escalate_to_human — STRICTLY MANDATORY: Before calling escalate_to_human, you MUST collect the visitor's name and email address, and call update_contact_profile to save/create their contact record. You are strictly forbidden from calling escalate_to_human unless their contact details (both name and email) have been saved first. Even if they request a human agent immediately, explain that you need their name and email to connect them, call update_contact_profile, and only then call escalate_to_human. This gate cannot be skipped by autonomy or urgency.
12. send_email — template "agent_verification_otp" vars {} for OTP. template "conversation_summary" vars {name, companyName, summary} for chat summary. Never invent templates.
13. verify_email_otp — call when user supplies 6-digit code. Only verified:true means success. Never validate OTP yourself, and never treat a plausible-looking code as verified without calling this.
14. web_crawl — only when user explicitly references a URL.

When a request needs information from multiple sources (e.g. checking conversation memory, searching FAQs, and searching uploaded knowledge), you should call all relevant tools in parallel in the same turn. The execution environment runs independent tools concurrently to minimize latency, so avoid sequential turn-by-turn tool chaining when tools can be run together.
</tools>`;